### ISSUE TITLE
Unable to Create Non-Loot Items on NPC Sheets

### ISSUE THREAD

**Issue by VoltCruelerz** [sdenec/tidy5e-sheet#246]
All items created by Tidy 5e on NPC sheets are merely loot items.  You can add other types of items to the sheet other ways, but you cannot create them natively.  This seems like an oversight.

**Comment by sdenec** [comment]
please check your tidy5e version. current version is. 0.4.14 - it seems you might have gotten stuck with 0.4.0 - in that cas please uninstall and reinstall.

**Comment by sdenec** [comment]
I guess this is solved, then.

**Comment by VoltCruelerz** [comment]
I do have 4.1.4, but I tried uninstalling and reinstalling Tidy5e Sheet.  The result is still the same.

### Character Sheet before adding item to inventory.
![image](https://user-images.githubusercontent.com/4068550/107952747-28fec800-6f68-11eb-83a6-615188af6bf0.png)

### After Add button pressed
![image](https://user-images.githubusercontent.com/4068550/107952832-459b0000-6f68-11eb-8d31-1f4ba9e4e459.png)

### New Loot Item
![image](https://user-images.githubusercontent.com/4068550/107952875-564b7600-6f68-11eb-8cfa-545cb9cc1acd.png)

At this point, the item is already classified as Loot, with no means of changing that.

**Comment by sdenec** [comment]
Ah, now I get what the issue is. That's nothing I can change as it's actually the default behaviour. The default shett does exactly the same. To get anything other than loot onto the npc you have to drag and drop a pre created item.
